### ISSUE TITLE
inline assembly not recognized

### ISSUE THREAD

**Issue by orotarobas** [cpldcpu/light_ws2812#101]
We're trying to build the project for LPC812 using IAR compiler but we get errors since the assembly instructions are not recognized.
What toolchain are we supposed to use in order to build the project for the LPC81x family?

**Comment by cpldcpu** [comment]
I used the NXP supplied IDE, which is based on GCC as far as I know. It's quite possible that the format of the inline assembler is different. Maybe it is possible to adjust the source?

**Comment by orotarobas** [comment]
is it the MCUXpresso (Netbeans based)?

Would you be so kindo to send the project or put it on github?

Bests

Lorenzo


------ Messaggio originale ------
Da "Tim" ***@***.***>
A "cpldcpu/light_ws2812" ***@***.***>
Cc "orotarobas" ***@***.***>; "Author" 
***@***.***>
Data 22/12/2022 19:14:46
Oggetto Re: [cpldcpu/light_ws2812] inline assembly not recognized (Issue 
#101)
