### ISSUE TITLE
attiny13a arduino ide, 9.6mhz 1200000

### ISSUE THREAD

**Issue by FreezyExp** [cpldcpu/light_ws2812#19]
So I gave this a shot:

    attiny13at9.name=ATtiny13 @ 9.6MHz (internal 9.6 MHz clock)
    attiny13at9.bootloader.low_fuses=0x7a //fuses still need to be set to this value
    attiny13at9.bootloader.high_fuses=0xff
    attiny13at9.upload.using=arduino:arduinoisp
    attiny13at9.upload.maximum_size=1024
    attiny13at9.build.mcu=attiny13
    attiny13at9.build.f_cpu=1200000
    attiny13at9.build.core=core13

But I guess the timings have not been updated for arduino ide yet.
Without knowing the exact workings of the code in the 'ws2812_sendarray_mask'
I would guess this needs attiny bit of love (see what I did there? ;-) )

comparing the light_ws2818 file to the others, there are some differences.
would it be enough to simply change the 
#define w_fixedlow    2
#define w_fixedhigh   4
#define w_fixedtotal  8   
?

Or are additional tweaks required to make this work?

I am only interrested in the ws2818b ;-) but I could work in some additional defines to make it a config option for end users if need be.

**Comment by FreezyExp** [comment]
I think I found the porblem, missing a 0 behind f_cpu

**Comment by cpldcpu** [comment]
Ok, looks like you figured it on your own.

In general: The library adapts to the clock automatically. You just have to make sure F_CPU is set correctly and that the device is clocked at >4 Mhz, or better, >8 MHz.

**Comment by FreezyExp** [comment]
Ended up adapting the bare AVR code as otherwise it would not fit on the tiny.
Did not take to long, but currently sitting at 828 bytes
