### ISSUE TITLE
APA102 lib support for (Arduino) Adalight / AmbiLED

### ISSUE THREAD

**Issue by Fid3lity** [cpldcpu/light_ws2812#21]
Hi,

I am completely new to C / Arduino and I've been looking for a solution to get my APA102 strip running with either Adalight or AmbiLED. Got a reply from Adafruit saying that they are not working on adding APA102 support themselves. Do you know how to get this to work?

**Comment by cpldcpu** [comment]
Hi, sorry, I don't even know what these are. You can surely use my lib to add APA102 support to another program, though.
