### ISSUE TITLE
Multiple strips at the same time

### ISSUE THREAD

**Issue by ajfisher** [cpldcpu/light_ws2812#26]
So I can see that by using `ws2812_setleds_pin` it's possible to have multiple strips on the one port be usable however from what I can understand of the code it appears as though these would be written
independently for each strip. 

EG: 3 strips, on pins 8, 9, 10 on Arduino (PORTB pins 0, 1, 2) 

I would then need to call `ws2812_setleds_pin` three times, once for each strip with appropriate array.

The question I have (and with a bit of guidance I can probably submit this as a change if it's possible) is whether it's possible to output different sequences to a single port all in one go and maintain the timings? 

Presumably this would involve maintaining a buffer of what the current bit is for each of the pins on the port being fed from each of the strip arrays and then writing that mask to the whole port in one go... or something?

Is that possible? Or is that what's happening now and I've missed that in the code?

Cheers
Andrew

**Comment by cpldcpu** [comment]
Sorry, currently the librariy is not able to output different data to multiple strings at the same time. Getting this done on an AVR is extremely hard, and it would only work work special cases.
