### ISSUE TITLE
Port to ESP8266

### ISSUE THREAD

**Issue by sfranzyshen** [cpldcpu/light_ws2812#27]
I have not looked further into your code ... but could this be ported over to operate on the ESP8266 micro controller?

**Comment by cpldcpu** [comment]
The common theme in this library is that it uses cycle-exact timing. This does only work when the timing of the cpu is deterministic, which is typically not the case anymore on faster MCUs, such as the ESP8266. On the ESP8266 it is better to use an approach that is not dependend on exact cpu timing.

There already seems to be a nice WS2812 drivers for the ESP8266, which uses the I2S peripheral:
https://github.com/cnlohr/esp8266ws2812i2s

I suggest to use that one - no need to reinvent the wheel.
