### ISSUE TITLE
Attiny13a LED light up incorrect colour

### ISSUE THREAD

**Issue by wilsonlih** [cpldcpu/light_ws2812#32]
I set my F_CPU=9600000 but the LED colour display wrong colour. Does this code support this MCU?

**Comment by cpldcpu** [comment]
Yes, there should be no issue. 

- Is the F_CPU setting global?
- Are the clock fuses in the ATtiny13 set correctly?

**Comment by wilsonlih** [comment]
I set the F_CPU under the project properties. And the CKSEL0 =0 and CKSEL1=1

**Comment by cpldcpu** [comment]
Then it should work. Have you tried to the troubleshooting list in the readme?

**Comment by Soldia1138** [comment]
Despite the issue being two months old: What about the CKDIV fuse bit? Did you deactivate it?
