### ISSUE TITLE
Would this work with WS2813?

### ISSUE THREAD

**Issue by briceparent** [cpldcpu/light_ws2812#34]
The new product WS2813 seems to be based on WS2811 and WS2812, both supported by this software. 
Is there (or will there be) any support for this 4-wire hardware?

I've ordered some strips, but I won't get them until some weeks, so I can't really make any test by now, but I'm already looking for solution (like an Attiny85 + this lib) to interface those strips with a Raspberry Pi.

**Comment by cpldcpu** [comment]
My WS2813 order also has not arrived yet.

From the datasheet it looks as if the protocol remained the same, so it should work with the one wire protocol as well. 

Extension to two wires would be required to take into account the situation where the first LED in the chain fails.

**Comment by Soldia1138** [comment]
Shouldn't be a problem if I interpret the dstasheet correctly. The second line is only for Backup Data.

**Comment by cpldcpu** [comment]
I tested it now. It works. The only modification is an increased reset time.
