### ISSUE TITLE
Impossible constraint in 'asm'

### ISSUE THREAD

**Issue by Eeeeevgen** [cpldcpu/light_ws2812#36]
While compiling there are warning and error:
../light_ws2812.c:119:5: warning: asm operand 2 probably doesn't match constraints
../light_ws2812.c:119:5: error: impossible constraint in 'asm'

Atmega128, AVR Studio 4.19, AVR Toolchain 3.3.0.364
The problem is in selected port, for some reason PORTF doesn't work. Any other port is correct. Can anyone explain this?

**Comment by cpldcpu** [comment]
Possibly "PORTF" can not be accessed with the OUT instruction because its address is outside of the I/O range?

**Comment by Eeeeevgen** [comment]
I hope I understood: ATmega128 has ATmega103 compatibility mode, in it port F is digital input only. I didn't find any settings in AVR Studio for this, but I think that is the answer.
