### ISSUE TITLE
Tiny error in example light_ws2812_AVR/Examples/Rainbow.c

### ISSUE THREAD

**Issue by oyooyo** [cpldcpu/light_ws2812#40]
In light_ws2812_AVR/Examples/Rainbow.c, COLORLENGTH and FADE are defined like this:
```
#define COLORLENGTH MAXPIX/2
#define FADE 256/COLORLENGTH
```
but these formulas should be set in brackets, because without doing so, FADE will be transformed to
256/MAXPIX/2
by the preprocessor, instead of
256/(MAXPIX/2)
as probably intended. One effect of the missing brackets is that this example code does not work if MAXPIX is set to 129 or greater, as in that case FADE would currently become zero.

**Comment by cpldcpu** [comment]
Thanks, added!
