### ISSUE TITLE
Examples not compiling

### ISSUE THREAD

**Issue by Kaes3kuch3n** [cpldcpu/light_ws2812#41]
I just wanted to try out the library in combination with an Arduino Uno and some WS 2812 LEDs, but it won't compile correctly.
Here's the error log: http://pastebin.com/0m6tqhb4

The last says: "Error while compiling for the board Arduino/Genuine Uno"

**Comment by Henri-K** [comment]
@Kaes3kuch3n the zipfile in the arduino folder is outdated. delete it and zip the folder within the directory instead. import this new zipfile into arduino as described in the readme.

**Comment by cpldcpu** [comment]
Good point. Need to fix it some time.

**Comment by manischewitzbacon** [comment]
i'm having trouble compiling examples as well - using ATTiny85 and i zipped the folder rather than using the zip in the zip.  

https://pastebin.com/MNCtfJMu

**Comment by cpldcpu** [comment]
this should be fixed now
