### ISSUE TITLE
Difference with STM32F3xxx?

### ISSUE THREAD

**Issue by rascafr** [cpldcpu/light_ws2812#45]
Thanks the huge work. Works well with STM32F0 devices, but not with STM32F3xx, the assembly code is stuck into an infinite loop. 

Tried to debug the code with OpenOCD, seems like the chip is blocked at the `ilop`end instruction.

Have you an idea about where the problem may come from? Is there such a huge difference between M0 and M3 assembly code instruction and how it works?

Regards

**Comment by cpldcpu** [comment]
Curious! No idea what the issue is. I have never tried it on CM3, but I believe others have. The CM3 is a superset of CM0.

One potential issue, however, is that the timing become more unpredictable with higher clocked CM3 MCUs, since there will be flash waitstates.

**Comment by rascafr** [comment]
Wow, thanks a lot for the quick answer! :)
I've changed the clockspeed of the STM32F303 (72MHz to 16MHz then 8MHz) but the problem is still here.

The assembly code seems to block in the bit 1 operation (`08000d2c` → `08000d34` → `08000d38` → `08000d40` → `08000d2c` → etc.), here is a copy of the disassembly code during debug:

![screenshot at 2017-03-01 21-46-01](https://cloud.githubusercontent.com/assets/12009083/23483100/68f4f6fa-fec9-11e6-8ed7-b100bb3263dd.png)

What do you mean by a register allocation issue? Register overridden?

Again, thanks a lot!

**Comment by cpldcpu** [comment]
It's most likely an issue with flash timing and code cache. The bitbanging approach is not very suitable for cores beyond CM0.
