### ISSUE TITLE
no arduino example compiles

### ISSUE THREAD

**Issue by autotel** [cpldcpu/light_ws2812#49]
error:

\WS2812.cpp:38:35: error: 'OFFSET_R' was not declared in this scope
   px_value.r = pixels[OFFSET_R(tmp)];

**Comment by autotel** [comment]
I think that the files included in the zip files are a wrong set. If I use the non-zipped files instead, it compiles

**Comment by andyface** [comment]
I agree with @autotel, the zipped files included in the arduino folder are different to the ones in the folder. zipping the folder and using that to include the library works.

Probably just needs the zip file updating

**Comment by cpldcpu** [comment]
Ì merged the pull request. Please test.
