### ISSUE TITLE
Add fast clear LEDs on AVR

### ISSUE THREAD

**Issue by GitMoDu** [cpldcpu/light_ws2812#55]
Is there way to just set all values to 0 and latch the WS2812? Faster than the simple way of filling the memory array with 0, of course.
As far as I can see from the documentation, we should be able to issue a minimal clear command (start writing 0 bit, wait 6 us for the chip to latch).

**Comment by cpldcpu** [comment]
The WS2812 will only latch complete data packets.

You can set all LEDs to the same color by calling "sendarray" in a loop. See "chained_writes" example.

**Comment by GitMoDu** [comment]
I was hoping for a faster way to do a clear, but sending the data array straight might just be good enough. Thanks, for pointing out the example of chained writes.
