### ISSUE TITLE
not compiling for SAMD11

### ISSUE THREAD

**Issue by perigalacticon** [cpldcpu/light_ws2812#57]
When compiling with a core for SAMD11 by MattairTech (https://github.com/mattairtech/ArduinoCore-samd) I get:
```
In file included from C:\Users\Perigalacticon\Documents\Arduino\sketches\Function Tests\test_neopixels_841\test_neopixels_841.ino:6:0:
C:\Program Files (x86)\Arduino\libraries\light_ws2812/WS2812.h:28:24: fatal error: util/delay.h: No such file or directory

 #include <util/delay.h>

                        ^
```
This might be an installation issue, but light_ws2812_cortex.h has #include "WS2812.h", which contains commands specific to AVR.

**Comment by cpldcpu** [comment]
The Arduino version only supports AVR for now. Sorry.
