### ISSUE TITLE
Asm code for GNU or keil?

### ISSUE THREAD

**Issue by roadna** [cpldcpu/light_ws2812#59]
Hi,
Very appreciated for your repo and asm solution.
I'm using STM32F0 and develop in Keil 5, when compiling the .c file, it pops up error. 
Refer to this [Link](https://devzone.nordicsemi.com/question/54805/mixing-c-assembly-in-keil-ide/), I'm in the same situation, but I'm not familiar to assmbly code so can't transform it. 
Could you tell your compiler environment, or any other info about learning this asm code?

Thanks

**Comment by cpldcpu** [comment]
Unfortunately keil uses a different inline assembler format. It will take some work to adapt it. Not sure anybody has done it so far.
