### ISSUE TITLE
Should an Atmega128 8MHz work?

### ISSUE THREAD

**Issue by alphalove** [cpldcpu/light_ws2812#63]
Hello,
I've tried a number of neopixel / ws2812 librarys (using MegaCore) in Arduino but can get none of them to work.  I've connected the neopixel to pin 5 (which is PE5 as per MegaCore pin allocation)

I've tried this library also and while it compile happily, when I load it to the board nothing happens.  I've confirmed the neopixels are ok using a 328p and an adafruit library.

Short of a CRO, is there anything else I should be checking to see if this is operational?  It seems the

Kind regards,

alex

**Comment by cpldcpu** [comment]
this sounds like a hardware issue. the library works fine with this config.
