### ISSUE TITLE
Atmega168

### ISSUE THREAD

**Issue by vSoulz** [cpldcpu/light_ws2812#64]
Hi, I have Adapixel neofruit ws2812 and AVR Atmega168. Tried to use Your library, but my stick is just light on red color. Tried every configuration but nothing. Can someone help me? leds is working because I can light 1-8 led, but when I loop lighting 2,4,8 leds then it's starting very good but after loop they are no turning off and still light 8 leds on red color.

**Comment by cpldcpu** [comment]
closing due to age.
