### ISSUE TITLE
Attiny10 with Arduino biduino10 core

### ISSUE THREAD

**Issue by dwhacks** [cpldcpu/light_ws2812#66]
Using this attiny10 board on arduino: https://github.com/kimio-kosaka/bitDuino10-arduinoTPI 

The compiled code is too large. Even the "Blinky" sketch in your examples works out to 1884 bytes. Any idea why this is?

**Comment by cpldcpu** [comment]
I have never used this. But, well, Arduino has a lot of overhead.  For small devices like the ATtiny10, I would reccommend to go to a direct C implementation.
