### ISSUE TITLE
Library and Examples not building

### ISSUE THREAD

**Issue by rkeithryan** [cpldcpu/light_ws2812#68]
Using an ATTiny85 and getting the following errors

> Building Library
> Light_WS2812/light_ws2812.h:69: warning: 'ws2812_setleds_pin' declared inline after being called
> Light_WS2812/light_ws2812.h:69: warning: previous declaration of 'ws2812_setleds_pin' was here
> Light_WS2812/light_ws2812.h:80: warning: 'ws2812_sendarray_mask' declared inline after being called
> Light_WS2812/light_ws2812.h:80: warning: previous declaration of 'ws2812_sendarray_mask' was here
> Building Rainbow
> Light_WS2812/light_ws2812.h:69: warning: 'ws2812_setleds_pin' declared inline after being called
> Light_WS2812/light_ws2812.h:69: warning: previous declaration of 'ws2812_setleds_pin' was here
> Light_WS2812/light_ws2812.h:80: warning: 'ws2812_sendarray_mask' declared inline after being called
> Light_WS2812/light_ws2812.h:80: warning: previous declaration of 'ws2812_sendarray_mask' was here
>    text    data     bss     dec     hex filename
>     642       0     114     756     2f4 Objects/Rainbow.o
>       0 [main] sh.exe" 13048 sync_with_child: child 14796(0x1DC) died before initialization with status code 0xC0000142
>     131 [main] sh.exe" 13048 sync_with_child: *** child state waiting for longjmp
> "D:/Program Files/utils/bin/sh.exe": fork: Resource temporarily unavailable
> make: *** [Rainbow] Error 128

Any suggestions?

**Comment by cpldcpu** [comment]
sorry, no idea right now. Which compiler are you using?

Closing due to age.
