### ISSUE TITLE
it disables the planned interrupt requests

### ISSUE THREAD

**Issue by ruchiMewada** [cpldcpu/light_ws2812#95]
under this library for ws2812
there is one function `ws2812_sendarray_mask` which at the start disables the interrupt requests

I can not disable the planned interrupts every time I try feeding the LED as per my requirements

so I commented on that part from the library and compiled it again.

now the LEDs randomly blink with any random color at any random time. 

for testing purposes, I am running the example code of this library

It still has the same behavior.

I don't understand which internal interrupt is interrupting the LED behavior which was previously disabled by the `cli()` function call.

**Comment by cpldcpu** [comment]
The library itself does not use interrupts, but its functionality is disrupted by interrupts. Unfortunately this problem can only be fixed in your source.
