### ISSUE TITLE
EFM8 support?

### ISSUE THREAD

**Issue by VORMie** [cpldcpu/light_ws2812#96]
Hey! I was wondering how I could get this working for an EFM8 module. I'm not used to the controller, and I'm not really sure how to get started with it to be honest. It would be awesome if I could get it working with my controller, but I can't understand where I'm supposed to change the code structure

**Comment by cpldcpu** [comment]
That's a 8051 based device? I have never used one. In principle, I guess, it would be possible to control WS2812 with them, but probably an assembler based solution is best.
