### ISSUE TITLE
Void zip file

### ISSUE THREAD

**Issue by Denibel** [cpldcpu/light_ws2812#99]
(https://github.com/cpldcpu/light_ws2812/tree/master/light_ws2812_Arduino)/light_WS2812.zip is void

**Comment by cpldcpu** [comment]
Where did you find that link?

This one works: https://github.com/cpldcpu/light_ws2812/blob/master/light_ws2812_Arduino/light_WS2812.zip

**Comment by Denibel** [comment]
Straightforward exploration down from https://github.com/cpldcpu/light_ws2812 : clicking in light_WS_Arduino, and then light_WS2812.zip ... However, I downloaded every revealent files one by one, and installed them manually in my Arduino IDE, it works ... Thanks for youy job !
